apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: order-ns
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Add this to your networkpolicy.yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-product-to-order
  namespace: order-ns
spec:
  podSelector:
    matchLabels:
      app: order-micro # Ensure this matches your Order deployment labels
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway-system
              # kubernetes.io/metadata.name: product-ns
      ports:
        - protocol: TCP
          port: 5000 # Or whatever port your Order service uses
