apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: order-ns
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allows the GKE Load Balancer/Gateway to reach the pod
      ports:
        - protocol: TCP
          port: 5000
---
# Add this to your networkpolicy.yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-product-to-order
  namespace: order-ns
spec:
  podSelector:
    matchLabels:
      app: order-micro # Ensure this matches your Order deployment labels
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: product-ns
      - namespaceSelector: # ADD THIS BLOCK
          matchLabels:
            kubernetes.io/metadata.name: frontend-ns
    ports:
      - protocol: TCP
        port: 5000
