apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-order-to-notification
  namespace: notification-ns 
spec:
  podSelector:
    matchLabels:
      tier: notification # Targets your Go pod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: order-ns 
      ports:
        - protocol: TCP
          port: 5001
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: notification-ns
spec:
  podSelector: {}
  policyTypes:
    - Ingress
