apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-micro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dev126712/microservice-charts-deployment.git
    targetRevision: HEAD
    path: frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
