kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: external-gateway-http
  annotations:
    networking.gke.io/certmap: store-example-com-map
spec:
  # This GatewayClass uses a global external Application Load Balancer.
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
  - name: http
    protocol: HTTP
    port: 8080
