apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: postgres-ns
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-ns
spec:
  serviceName: "postgres-headless"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
          - containerPort: 5432
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            value: "pass"
        envFrom:
          - configMapRef:
              name: postgres-config # Fixed Indentation
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres-data
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-ns
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass
  POSTGRES_DB: orders_db
